services:
  - type: web
    name: healthflow-backend
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mainline.proxy.rlwy.net:55062/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: tMkhNQzLyUsEfkOmLkhgCvcsNkfCjDoe